### ISSUE TITLE
Power Bank Compatibility

### ISSUE THREAD

**Issue by Kalak85** [TuriSc/grimmboy#1]
Hello, I am very much a novice with electronics but would like to build one of these for my son. I am wondering if a power bank would be compatible to replace the 18650 (and TP4056?). I only see 5V ones and it looks like the circuit runs off 3.3V so I don't know.

Thanks!

**Comment by TuriSc** [comment]
You can. You could strip one end of a USB cable and connect its V+ and GND to the Arduino's 5V and GND pins respectively.
It's not the most efficient way and it relies on the power bank having overvoltage protection circuitry (most, but not all do).
I also suggest you have a read at the official documentation here: https://docs.arduino.cc/learn/electronics/power-pins/

Have fun with your projects :)
